--[[
	© 2015 CloudSixteen.com do not share, re-distribute or modify
	without permission of its author (kurozael@gmail.com).

	Clockwork was created by Conna Wiles (also known as kurozael.)
	http://cloudsixteen.com/license/clockwork.html
--]]

local FACTION = Clockwork.faction:New("Survivor");

FACTION.useFullName = true;
FACTION.material = "severance/factions/survivor";
FACTION.models = {
	female = {
		"models/humans/group34/female_01.mdl",
		"models/humans/group34/female_02.mdl",
		"models/humans/group34/female_03.mdl",
		"models/humans/group34/female_04.mdl",
		"models/humans/group34/female_06.mdl",
		"models/humans/group34/female_07.mdl",
		"models/humans/group35/female_01.mdl",
		"models/humans/group35/female_02.mdl",
		"models/humans/group35/female_03.mdl",
		"models/humans/group35/female_04.mdl",
		"models/humans/group35/female_06.mdl",
		"models/humans/group35/female_07.mdl",
		"models/humans/group36/female_01.mdl",
		"models/humans/group36/female_02.mdl",
		"models/humans/group36/female_03.mdl",
		"models/humans/group36/female_04.mdl",
		"models/humans/group36/female_06.mdl",
		"models/humans/group36/female_07.mdl",
		"models/humans/group37/female_01.mdl",
		"models/humans/group37/female_02.mdl",
		"models/humans/group37/female_03.mdl",
		"models/humans/group37/female_04.mdl",
		"models/humans/group37/female_06.mdl",
		"models/humans/group37/female_07.mdl",
		"models/humans/group38/female_01.mdl",
		"models/humans/group38/female_02.mdl",
		"models/humans/group38/female_03.mdl",
		"models/humans/group38/female_04.mdl",
		"models/humans/group38/female_06.mdl",
		"models/humans/group38/female_07.mdl",
		"models/humans/group39/female_01.mdl",
		"models/humans/group39/female_02.mdl",
		"models/humans/group39/female_03.mdl",
		"models/humans/group39/female_04.mdl",
		"models/humans/group39/female_06.mdl",
		"models/humans/group39/female_07.mdl",
		"models/humans/group40/female_01.mdl",
		"models/humans/group40/female_02.mdl",
		"models/humans/group40/female_03.mdl",
		"models/humans/group40/female_04.mdl",
		"models/humans/group40/female_06.mdl",
		"models/humans/group40/female_07.mdl",
		"models/humans/group41/female_01.mdl",
		"models/humans/group41/female_02.mdl",
		"models/humans/group41/female_03.mdl",
		"models/humans/group41/female_04.mdl",
		"models/humans/group41/female_06.mdl",
		"models/humans/group41/female_07.mdl"
	},
	male = {
		"models/humans/group34/male_01.mdl",
		"models/humans/group34/male_02.mdl",
		"models/humans/group34/male_03.mdl",
		"models/humans/group34/male_04.mdl",
		"models/humans/group34/male_05.mdl",
		"models/humans/group34/male_06.mdl",
		"models/humans/group34/male_07.mdl",
		"models/humans/group34/male_08.mdl",
		"models/humans/group34/male_09.mdl",
		"models/humans/group35/male_01.mdl",
		"models/humans/group35/male_02.mdl",
		"models/humans/group35/male_03.mdl",
		"models/humans/group35/male_04.mdl",
		"models/humans/group35/male_05.mdl",
		"models/humans/group35/male_06.mdl",
		"models/humans/group35/male_07.mdl",
		"models/humans/group35/male_08.mdl",
		"models/humans/group35/male_09.mdl",
		"models/humans/group36/male_01.mdl",
		"models/humans/group36/male_02.mdl",
		"models/humans/group36/male_03.mdl",
		"models/humans/group36/male_04.mdl",
		"models/humans/group36/male_05.mdl",
		"models/humans/group36/male_06.mdl",
		"models/humans/group36/male_07.mdl",
		"models/humans/group36/male_08.mdl",
		"models/humans/group36/male_09.mdl",
		"models/humans/group37/male_01.mdl",
		"models/humans/group37/male_02.mdl",
		"models/humans/group37/male_03.mdl",
		"models/humans/group37/male_04.mdl",
		"models/humans/group37/male_05.mdl",
		"models/humans/group37/male_06.mdl",
		"models/humans/group37/male_07.mdl",
		"models/humans/group37/male_08.mdl",
		"models/humans/group37/male_09.mdl",
		"models/humans/group38/male_01.mdl",
		"models/humans/group38/male_02.mdl",
		"models/humans/group38/male_03.mdl",
		"models/humans/group38/male_04.mdl",
		"models/humans/group38/male_05.mdl",
		"models/humans/group38/male_06.mdl",
		"models/humans/group38/male_07.mdl",
		"models/humans/group38/male_08.mdl",
		"models/humans/group38/male_09.mdl",
		"models/humans/group39/male_01.mdl",
		"models/humans/group39/male_02.mdl",
		"models/humans/group39/male_03.mdl",
		"models/humans/group39/male_04.mdl",
		"models/humans/group39/male_05.mdl",
		"models/humans/group39/male_06.mdl",
		"models/humans/group39/male_07.mdl",
		"models/humans/group39/male_08.mdl",
		"models/humans/group39/male_09.mdl",
		"models/humans/group40/male_01.mdl",
		"models/humans/group40/male_02.mdl",
		"models/humans/group40/male_03.mdl",
		"models/humans/group40/male_04.mdl",
		"models/humans/group40/male_05.mdl",
		"models/humans/group40/male_06.mdl",
		"models/humans/group40/male_07.mdl",
		"models/humans/group40/male_08.mdl",
		"models/humans/group40/male_09.mdl",
		"models/humans/group41/male_01.mdl",
		"models/humans/group41/male_02.mdl",
		"models/humans/group41/male_03.mdl",
		"models/humans/group41/male_04.mdl",
		"models/humans/group41/male_05.mdl",
		"models/humans/group41/male_06.mdl",
		"models/humans/group41/male_07.mdl",
		"models/humans/group41/male_08.mdl",
		"models/humans/group41/male_09.mdl"
	};
};

FACTION_SURVIVOR = FACTION:Register();