SS.Awards.Add("Best Builder")
SS.Awards.Add("Best Car")
SS.Awards.Add("Best Plane")
SS.Awards.Add("Best Contraption")
SS.Awards.Add("Best Base")
SS.Awards.Add("Best Trap")
SS.Awards.Add("Best Hideout")
SS.Awards.Add("Most Craziest Contraption")
SS.Awards.Add("Most Craziest Vehicle")
SS.Awards.Add("Most Laggiest Player")
SS.Awards.Add("Most Laggiest Contraption")
SS.Awards.Add("Most Deadliest Weapon")
SS.Awards.Add("Most Defensive Base")
SS.Awards.Add("Most Useful Contraption")
SS.Awards.Add("Most Destructive Contraption")