--[[
Name: "sv_enum.lua".
Product: "kuroScript".
--]]

-- Set some information.
PREC_NIGHT_TIME_RAIN = 1;
PREC_DAY_TIME_RAIN = 2;
PREC_EVENING_RAIN = 3;
PREC_MORNING_RAIN = 4;
PREC_STORM_RAIN = 5;

-- Set some information.
DAY_LENGTH = 1440;
NOON_EXACT = 720;
DAWN_EXACT = 360;
DUSK_EXACT = 1080;
DAWN_START = 216;
DUSK_START = 936;
DAY_START = 300;
DAWN_END = 504;
DUSK_END = 1224;
DAY_END = 1110;