--[[
	© 2011 CloudSixteen.com do not share, re-distribute or modify
	without permission of its author (kurozael@gmail.com).
--]]

CloudScript.config:AddSystem("mysql_characters_table", "The name of the table where the character data is stored.");
CloudScript.config:AddSystem("mysql_players_table", "The name of the table where the player data is stored.");
CloudScript.config:AddSystem("mysql_username", "The username that you log in to MySQL with.");
CloudScript.config:AddSystem("mysql_password", "The password that you log in to MySQL with.");
CloudScript.config:AddSystem("mysql_database", "The name of the database that we'll be using.");
CloudScript.config:AddSystem("mysql_host", "The host that your MySQL database is located.");
CloudScript.config:AddSystem("scale_attribute_progress", "The amount to scale attribute progress by.");
CloudScript.config:AddSystem("messages_must_see_player", "The amount to scale attribute progress by.");
CloudScript.config:AddSystem("messages_must_see_player", "Whether or not you must see a player to hear some in-character messages.");
CloudScript.config:AddSystem("default_attribute_points", "The default amount of attribute points that a player has.");
CloudScript.config:AddSystem("enable_temporary_damage", "Whether or not temporary damage is enabled.");
CloudScript.config:AddSystem("enable_prop_protection", "Whether or not to enable prop protection.");
CloudScript.config:AddSystem("use_local_machine_date", "Whether or not to use the local machine's date when the map is loaded.");
CloudScript.config:AddSystem("use_local_machine_time", "Whether or not to use the local machine's time when the map is loaded.");
CloudScript.config:AddSystem("use_opens_entity_menus", "Whether or not 'use' opens the context menus.");
CloudScript.config:AddSystem("shoot_after_raise_time", "The time that it takes for players to be able to shoot after raising their weapon (seconds).\nSet to 0 for no time.");
CloudScript.config:AddSystem("use_own_group_system", "Whether or not you use a different group or admin system to CloudScript.");
CloudScript.config:AddSystem("save_recognised_names", "Whether or not recognised names should be saved.");
CloudScript.config:AddSystem("save_attribute_boosts", "Whether or not attribute boosts are saved.");
CloudScript.config:AddSystem("ragdoll_immunity_time", "The time that a player's ragdoll is immune from damage (seconds).");
CloudScript.config:AddSystem("additional_characters", "The additional amount of characters that each player can have.");
CloudScript.config:AddSystem("change_class_interval", "The time that a player has to wait to change class again (seconds).", 0, 7200);
CloudScript.config:AddSystem("sprint_lowers_weapon", "Whether or not sprinting lowers a player's weapon.");
CloudScript.config:AddSystem("raised_weapon_system", "Whether or not the raised weapon system is enabled.");
CloudScript.config:AddSystem("prop_kill_protection", "Whether or not prop kill protection is enabled.");
CloudScript.config:AddSystem("CloudScript_intro_enabled", "Enable the CloudScript introduction for new players.");
CloudScript.config:AddSystem("use_optimised_rates", "Whether or not to use CloudScript optimised rates.");
CloudScript.config:AddSystem("generator_interval", "The time that it takes for generator cash to be distrubuted (seconds).", 0, 7200);
CloudScript.config:AddSystem("enable_gravgun_punt", "Whether or not to enable entities to be punted with the gravity gun.");
CloudScript.config:AddSystem("default_inv_weight", "The default inventory weight (kilograms).");
CloudScript.config:AddSystem("save_data_interval", "The time that it takes for data to be saved (seconds).", 0, 7200);
CloudScript.config:AddSystem("damage_view_punch", "Whether or not a player's view gets punched when they take damage.");
CloudScript.config:AddSystem("unrecognised_name", "The name that is given to unrecognised players.");
CloudScript.config:AddSystem("limb_damage_system", "Whether or not limb damage is enabled.");
CloudScript.config:AddSystem("scale_fall_damage", "The amount to scale fall damage by.");
CloudScript.config:AddSystem("default_cash", "The default amount of cash that each player starts with.", 0, 10000);
CloudScript.config:AddSystem("armor_chest_only", "Whether or not armor only affects the chest.");
CloudScript.config:AddSystem("minimum_physdesc", "The minimum amount of characters a player must have in their physical description.", 0, 128);
CloudScript.config:AddSystem("wood_breaks_fall", "Whether or not wooden physics entities break a player's fall.");
CloudScript.config:AddSystem("enable_vignette", "Whether or not the vignette is enabled.");
CloudScript.config:AddSystem("enable_heartbeat", "Whether or not the heartbeat is enabled.");
CloudScript.config:AddSystem("enable_crosshair", "Whether or not the crosshair is enabled.");
CloudScript.config:AddSystem("use_free_aiming", "Whether or not free aiming is enabled.");
CloudScript.config:AddSystem("recognise_system", "Whether or not the recognise system is enabled.");
CloudScript.config:AddSystem("cash_enabled", "Whether or not cash is enabled.");
CloudScript.config:AddSystem("default_physdesc", "The physical description that each player begins with.");
CloudScript.config:AddSystem("scale_chest_dmg", "The amount to scale chest damage by.");
CloudScript.config:AddSystem("body_decay_time", "The time that it takes for a player's ragdoll to decay (seconds).", 0, 7200);
CloudScript.config:AddSystem("banned_message", "The message that a player receives when trying to join while banned.\n!t for the time left, !f for the time format.");
CloudScript.config:AddSystem("wages_interval", "The time that it takes for wages cash to be distrubuted (seconds).", 0, 7200);
CloudScript.config:AddSystem("scale_prop_cost", "How to much to scale prop cost by.\nSet to 0 to to make props free.");
CloudScript.config:AddSystem("fade_dead_npcs", "Whether or not to fade dead NPCs.");
CloudScript.config:AddSystem("cash_weight", "The weight of cash (kilograms).", 0, 100, 3);
CloudScript.config:AddSystem("scale_head_dmg", "The amount to scale head damage by.");
CloudScript.config:AddSystem("block_inv_binds", "Whether or not inventory binds should be blocked for players.");
CloudScript.config:AddSystem("scale_limb_dmg", "The amount to scale limb damage by.");
CloudScript.config:AddSystem("enable_headbob", "Whether or not to enable headbob.");
CloudScript.config:AddSystem("command_prefix", "The prefix that is used for chat commands.");
CloudScript.config:AddSystem("crouched_speed", "The speed that characters walk at when crouched.", 0, 1024);
CloudScript.config:AddSystem("owner_steamid", "The Steam ID of the server owner.");
CloudScript.config:AddSystem("default_flags", "The flags that each player begins with.");
CloudScript.config:AddSystem("disable_sprays", "Whether players can spray their tags.");
CloudScript.config:AddSystem("hint_interval", "The time that a hint is displayed to each player (seconds).", 0, 7200);
CloudScript.config:AddSystem("ooc_interval", "The time that a player has to wait to speak out-of-character again (seconds).\nSet to 0 for never.", 0, 7200);
CloudScript.config:AddSystem("minute_time", "The time that it takes for a minute to pass (seconds).", 0, 7200);
CloudScript.config:AddSystem("unlock_time", "The time that a player has to wait to unlock a door (seconds).", 0, 7200);
CloudScript.config:AddSystem("local_voice", "Whether or not to enable local voice.");
CloudScript.config:AddSystem("talk_radius", "The radius of each player that other characters have to be in to hear them talk (units).", 0, 4096);
CloudScript.config:AddSystem("give_hands", "Whether or not to give hands to each player.");
CloudScript.config:AddSystem("give_keys", "Whether or not to give keys to each player.");
CloudScript.config:AddSystem("wages_name", "The name that is given to wages.");
CloudScript.config:AddSystem("jump_power", "The power that characters jump at.", 0, 1024);
CloudScript.config:AddSystem("spawn_time", "The time that a player has to wait before they can spawn again (seconds).", 0, 7200);
CloudScript.config:AddSystem("walk_speed", "The speed that characters walk at.", 0, 1024);
CloudScript.config:AddSystem("run_speed", "The speed that characters run at.", 0, 1024);
CloudScript.config:AddSystem("door_cost", "The amount of cash that each door costs.");
CloudScript.config:AddSystem("lock_time", "The time that a player has to wait to lock a door (seconds).", 0, 7200);
CloudScript.config:AddSystem("max_doors", "The maximum amount of doors a player can own.");