--[[
Name: "sv_config.lua".
Product: "nexus".
--]]

nexus.config.Add("mysql_characters_table", "characters", nil, nil, true, true, true);
nexus.config.Add("mysql_players_table", "players", nil, nil, true, true, true);
nexus.config.Add("mysql_username", "", nil, nil, true, true, true);
nexus.config.Add("mysql_password", "", nil, nil, true, true, true);
nexus.config.Add("mysql_database", "", nil, nil, true, true, true);
nexus.config.Add("mysql_host", "", nil, nil, true, true, true);
nexus.config.Add("scale_attribute_progress", 1);
nexus.config.Add("messages_must_see_player", false, true);
nexus.config.Add("default_attribute_points", 30, true);
nexus.config.Add("enable_temporary_damage", true);
nexus.config.Add("enable_prop_protection", true);
nexus.config.Add("use_local_machine_date", false, nil, nil, nil, nil, true);
nexus.config.Add("use_local_machine_time", false, nil, nil, nil, nil, true);
nexus.config.Add("use_opens_entity_menus", true, true);
nexus.config.Add("shoot_after_raise_time", 1);
nexus.config.Add("save_recognised_names", true);
nexus.config.Add("save_attribute_boosts", false);
nexus.config.Add("ragdoll_immunity_time", 0.5);
nexus.config.Add("additional_characters", 2, true);
nexus.config.Add("change_class_interval", 180);
nexus.config.Add("raised_weapon_system", true, true);
nexus.config.Add("prop_kill_protection", true);
nexus.config.Add("nexus_intro_enabled", true);
nexus.config.Add("use_optimised_rates", true, nil, nil, nil, nil, true);
nexus.config.Add("generator_interval", 720);
nexus.config.Add("enable_gravgun_punt", true);
nexus.config.Add("default_inv_weight", 20, true);
nexus.config.Add("save_data_interval", 180);
nexus.config.Add("damage_view_punch", true);
nexus.config.Add("unrecognised_name", "Somebody you do not recognise.", true);
nexus.config.Add("scale_fall_damage", 1);
nexus.config.Add("default_cash", 40);
nexus.config.Add("armor_chest_only", false);
nexus.config.Add("minimum_physdesc", 32, true);
nexus.config.Add("wood_breaks_fall", true);
nexus.config.Add("enable_crosshair", true, true);
nexus.config.Add("recognise_system", true, true);
nexus.config.Add("cash_enabled", true, true, nil, nil, nil, true);
nexus.config.Add("default_physdesc", "", true);
nexus.config.Add("scale_chest_dmg", 1);
nexus.config.Add("body_decay_time", 600);
nexus.config.Add("banned_message", "You are still banned for !t more !f.");
nexus.config.Add("wages_interval", 720);
nexus.config.Add("scale_prop_cost", 1);
nexus.config.Add("fade_dead_npcs", true, true);
nexus.config.Add("cash_weight", 0.001, true);
nexus.config.Add("scale_head_dmg", 4);
nexus.config.Add("block_inv_binds", true, true);
nexus.config.Add("scale_limb_dmg", 0.5);
nexus.config.Add("enable_headbob", true, true);
nexus.config.Add("command_prefix", "/", true);
nexus.config.Add("crouched_speed", 25);
nexus.config.Add("default_flags", "", true);
nexus.config.Add("disable_sprays", true);
nexus.config.Add("hint_interval", 30);
nexus.config.Add("ooc_interval", 120);
nexus.config.Add("minute_time", 60, true);
nexus.config.Add("unlock_time", 3);
nexus.config.Add("local_voice", true, true);
nexus.config.Add("talk_radius", 384, true);
nexus.config.Add("wages_name", "Wages", true);
nexus.config.Add("jump_power", 160);
nexus.config.Add("spawn_time", 60);
nexus.config.Add("walk_speed", 100);
nexus.config.Add("run_speed", 225);
nexus.config.Add("door_cost", 10, true);
nexus.config.Add("lock_time", 2);
nexus.config.Add("max_doors", 5);